In [16]:
from concurrent.futures import ThreadPoolExecutor
from camoufox.sync_api import Camoufox
import asyncio
import sys
import os
import io
import zipfile
import pandas as pd
from curl_cffi import requests
from bs4 import BeautifulSoup

In [2]:
# Letterboxd Credentials
USERNAME = os.environ.get('letterboxd_username')
PASSWORD = os.environ.get('letterboxd_password')

if not USERNAME:
    raise ValueError("Username environment variable not found!")
if not PASSWORD:
    raise ValueError("Password environment variable not found!")

### Get Letterboxd zip-file and data

In [5]:
def run_full_download():
    # Fix for Windows asyncio subprocesses in background threads
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
    
    print("[INFO] Launching Camoufox...")
    with Camoufox(headless=True) as browser:
        page = browser.new_page()

        # ----------------------------------------------------------------------
        # Sign in
        print("[INFO] Navigating to Sign-In page...")
        page.goto("https://letterboxd.com/sign-in/", wait_until="networkidle")
        
        page.fill("input[name='username']", USERNAME)
        page.fill("input[name='password']", PASSWORD)

        # Click the explicit submit button
        page.click("button[type='submit']")
        page.wait_for_timeout(3000)
        
        page.wait_for_url(lambda url: "sign-in" not in url, timeout=10000)
        print("[INFO] Logged in successfully!")

        # ----------------------------------------------------------------------
        # Export browser session details for curl
        user_agent = page.evaluate("navigator.userAgent")
        cookies = page.context.cookies()

        # ----------------------------------------------------------------------
        # 2. Go to data settings
        print("[INFO] Navigating to Data Settings page...")
        page.goto("https://letterboxd.com/settings/data/", wait_until="networkidle")
        
        # 3. Click initial trigger to open the Colorbox modal
        print("[INFO] Opening Colorbox modal...")
        page.eval_on_selector("a.export-data-link", "el => el.click()")

        # ----------------------------------------------------------------------
        # 4. Wait for the modal container to appear and click the inner confirmation button/link
        print("[INFO] Waiting for modal and clicking confirm download...")
        # Colorbox wraps popups inside #colorbox or #cboxLoadedContent
        page.wait_for_selector("#colorbox", state="visible", timeout=10000)
        
        # Capture the file download triggered by clicking the modal's download button
        with page.expect_download(timeout=20000) as download_info:
            # Targets the confirmation button/link inside the open modal
            page.click("#colorbox a, #colorbox button, #cboxLoadedContent a")
        
        # 5. Save ZIP archive
        download = download_info.value
        print("[INFO] Downloaded zip-file successfully!")

        # Read the temporary file stream into an in-memory BytesIO buffer
        with open(download.path(), "rb") as f:
            zip_buffer = io.BytesIO(f.read())

        # Return buffered data, user_agent and cookies
        return zip_buffer, (user_agent, cookies)

# Execute in ThreadPoolExecutor for Jupyter compatibility
with ThreadPoolExecutor(max_workers=1) as executor:
    download, session_info = executor.submit(run_full_download).result()

# Extract lists from downloaded zip-file
with zipfile.ZipFile(download) as z:
    print("[INFO] Unzipping file content...")
    with z.open("watched.csv") as f:
        df_watched = pd.read_csv(f)
        df_watched.attrs = {
            'name':'watched',
            'primary_key':['letterboxd_uri']
            }

    with z.open("ratings.csv") as f:
        df_ratings = pd.read_csv(f)
        df_ratings.attrs = {
            'name':'ratings',
            'primary_key':['letterboxd_uri','rating']
            }

    with z.open("watchlist.csv") as f:
        df_watchlist = pd.read_csv(f)
        df_watchlist.attrs = {
            'name':'watchlist',
            'primary_key':['letterboxd_uri']
            }

    with z.open("lists/br-collection.csv") as f:
        df_br_collection = pd.read_csv(
            f,
            skiprows=4,
            usecols=[1,2,3]
            )
        df_br_collection = df_br_collection.rename(columns={'URL':'Letterboxd URI'})
        df_br_collection.attrs = {
            'name':'br_collection',
            'primary_key':['letterboxd_uri']
            }

    print("[INFO] File content unzipped successfully!")

[INFO] Launching Camoufox...
[INFO] Navigating to Sign-In page...
[INFO] Logged in successfully!
[INFO] Navigating to Data Settings page...
[INFO] Opening Colorbox modal...
[INFO] Waiting for modal and clicking confirm download...
[INFO] Downloaded zip-file successfully!
[INFO] Unzipping file content...
[INFO] File content unzipped successfully!

In [8]:
df_watchlist

           Date                              Name  Year        Letterboxd URI
0    2024-02-04      Colossus: The Forbin Project  1970  https://boxd.it/1Nmw
1    2024-02-04                               Her  2013  https://boxd.it/4O24
2    2024-02-04  Once Upon a Time... in Hollywood  2019  https://boxd.it/gH0O
3    2024-02-04                          Napoleon  2023  https://boxd.it/shJM
4    2024-02-04                     Asteroid City  2023  https://boxd.it/s3ds
..          ...                               ...   ...                   ...
352  2026-08-21                      3:10 to Yuma  2007  https://boxd.it/23g0
353  2026-08-22                The Way of the Gun  2000  https://boxd.it/28t4
354  2026-08-25                 American Gangster  2007  https://boxd.it/23wi
355  2026-08-25           Searching for Sugar Man  2012  https://boxd.it/2Y3s
356  2026-08-25                  T2 Trainspotting  2017  https://boxd.it/5vTA

[357 rows x 4 columns]

In [ ]:
user_agent = session_info[0]
cookies = session_info[1]

# Create session
session = requests.Session(impersonate="chrome124")

# 1. Update User-Agent
session.headers.update({"User-Agent": user_agent})

# 2. Add all 9 cookies at once
for cookie in cookies:
    session.cookies.set(
        name=cookie["name"],
        value=cookie["value"],
        domain=cookie.get("domain"),
        path=cookie.get("path", "/")
    )

# Now make your requests
res = session.get("https://boxd.it/h4cS")
print(res.status_code)  # Should be 200

200

In [47]:
soup = BeautifulSoup(res.text, "html.parser")

movie_metadata = {}

# Rating
val = (
    soup
    .find("meta", attrs={"name": "twitter:data2"})
    .get("content")
    .split("out of")[0]
)
movie_metadata['letterboxd_rating'] = float(val)

# Description
val = (
    soup
    .find("meta", attrs={"name": "twitter:description"})
    .get("content")
)
movie_metadata['description'] = val

# Background image
soup.find("meta", attrs={"property": "og:image"})
# Footer (contains duration)
soup.find(class_="text-link text-footer")

movie_metadata

{'letterboxd_rating': 3.85,
 'description': 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.'}

### Extract good movies and built shopping list

In [55]:
df_good_movies = df_ratings[df_ratings['Rating']>=3.5]
print(f"[INFO] Found {df_good_movies.shape[0]} good movies!")

# Build selector to remove movies already in BR collection from good movie list
sel = ~df_good_movies['Letterboxd URI'].isin(df_br_collection['URL'])

df_to_buy = (
    df_good_movies
    .loc[sel,:]
)

print(f"[INFO] {df_to_buy.shape[0]} movies could be bought!")

[INFO] Found 359 good movies!
[INFO] 226 movies could be bought!

In [56]:
df_to_buy.sort_values(['Rating','Name'],ascending=[False, True])

,Date,Name,Year,Letterboxd URI,Rating
438,2024-06-20,Cowboy Bebop,1998,https://boxd.it/ptES,5.0
50,2024-02-04,Galaxy Quest,1999,https://boxd.it/29gq,5.0
606,2025-08-17,Mare of Easttown,2021,https://boxd.it/u2h8,5.0
154,2024-02-04,The Banshees of Inisherin,2022,https://boxd.it/p7XS,5.0
572,2025-06-07,Black Mirror: San Junipero,2016,https://boxd.it/k4aS,4.5
...,...,...,...,...,...
344,2024-02-11,Tucker and Dale vs. Evil,2010,https://boxd.it/Mce,3.5
431,2024-05-27,Unbroken,2014,https://boxd.it/6IaA,3.5
452,2024-07-25,Under the Skin,2013,https://boxd.it/3mDa,3.5
456,2024-07-29,Upgrade,2018,https://boxd.it/i4gW,3.5
474,2024-09-10,Wind River,2017,https://boxd.it/dR3i,3.5

### Write to postgres

In [57]:
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import insert
from datetime import datetime
import pytz

In [58]:
PG_PASSWORD = os.environ.get('postgres_password')

if not PG_PASSWORD:
    raise ValueError("Postgres password environment variable not found!")

In [ ]:
def build_on_conflict_do_nothing(pk_columns, table_name="table"):
    """
    Method to avoid conflicts when trying to insert data with existing primary key values.
    Does nothing if PK already exists.
    Adds data if PK does not exist.
    """
    # Ensure pk_columns is a flat list
    if isinstance(pk_columns, str):
        target_elements = [pk_columns]
    else:
        target_elements = list(pk_columns)

    def insert_fn(table, conn, keys, data_iter):
        data = [dict(zip(keys, row)) for row in data_iter]
        
        # If there's no data to insert, log and return early
        if not data:
            print(f"[INFO] [{table_name}] No rows provided to insert.")
            return 0

        stmt = insert(table.table).values(data).on_conflict_do_nothing(
            index_elements=target_elements
        )
        
        result = conn.execute(stmt)
        inserted_count = result.rowcount
        total_rows = len(data)
        skipped_count = total_rows - inserted_count

        # Log or print the insertion breakdown
        if inserted_count > 0:
            print(f"[INFO] [{table_name}] Successfully inserted {inserted_count} new row(s) out of {total_rows}.")
        else:
            print(f"[INFO]  [{table_name}] 0 new rows inserted ({skipped_count} row(s) already existed).")

        return inserted_count

    return insert_fn

# ------------------------------------------------------------------------------------------
def write_df_to_postgres(df, schema, engine):
    """
    Function that actually writes data to postgres DB.
    """
    df_write = df.copy()
    df_write.columns = [c.lower().replace(' ','_') for c in df_write.columns]

    print("Columns:")
    print("\n".join(df_write.columns))

    # Convert date-column to datetime
    try:
        df_write['date'] = pd.to_datetime(df_write['date'])
    except:
        print("Conversion to datetime either failed or no date column available!")

    # Add load timestamp with timezone
    tz = pytz.timezone('Europe/Berlin')
    df_write['load_timestamp'] = datetime.now(tz)

    # Write dataframe to postgres DB
    df_write.to_sql(
        name=df_write.attrs['name'],  # Target table name
        schema=schema,
        con=engine,
        if_exists="append",        # 'fail' raises an error if table exists; use 'append' for daily runs
        index=False,              # Exclude the DataFrame index integer column
        method=build_on_conflict_do_nothing(
            pk_columns=df_write.attrs['primary_key'],
            table_name=df_write.attrs['name'])
    )

    return df_write

# ------------------------------------------------------------------------------------------
# WRITE DATA TO POSTGRES

# Create connection engine for postgres
engine = create_engine(f"postgresql://postgres:{PG_PASSWORD}@localhost:5432/moviedata")

write_df_to_postgres(df_watched, schema="letterboxd", engine=engine)
write_df_to_postgres(df_ratings, schema="letterboxd", engine=engine)
write_df_to_postgres(df_br_collection, schema="letterboxd", engine=engine)
write_df_to_postgres(df_watchlist, schema="letterboxd", engine=engine)

Columns:
date
name
year
letterboxd_uri
[INFO]  [watched] 0 new rows inserted (747 row(s) already existed).
Columns:
date
name
year
letterboxd_uri
rating
[INFO]  [ratings] 0 new rows inserted (682 row(s) already existed).
Columns:
name
year
letterboxd_uri
Conversion to datetime either failed or no date column available!
[INFO]  [br_collection] 0 new rows inserted (250 row(s) already existed).
Columns:
date
name
year
letterboxd_uri
[INFO]  [watchlist] 0 new rows inserted (357 row(s) already existed).

,date,name,year,letterboxd_uri,load_timestamp
0,2024-02-04,Colossus: The Forbin Project,1970,https://boxd.it/1Nmw,2026-08-24 21:54:05.160714+02:00
1,2024-02-04,Her,2013,https://boxd.it/4O24,2026-08-24 21:54:05.160714+02:00
2,2024-02-04,Once Upon a Time... in Hollywood,2019,https://boxd.it/gH0O,2026-08-24 21:54:05.160714+02:00
3,2024-02-04,Napoleon,2023,https://boxd.it/shJM,2026-08-24 21:54:05.160714+02:00
4,2024-02-04,Asteroid City,2023,https://boxd.it/s3ds,2026-08-24 21:54:05.160714+02:00
...,...,...,...,...,...
352,2026-08-21,3:10 to Yuma,2007,https://boxd.it/23g0,2026-08-24 21:54:05.160714+02:00
353,2026-08-22,The Way of the Gun,2000,https://boxd.it/28t4,2026-08-24 21:54:05.160714+02:00
354,2026-08-25,American Gangster,2007,https://boxd.it/23wi,2026-08-24 21:54:05.160714+02:00
355,2026-08-25,Searching for Sugar Man,2012,https://boxd.it/2Y3s,2026-08-24 21:54:05.160714+02:00
356,2026-08-25,T2 Trainspotting,2017,https://boxd.it/5vTA,2026-08-24 21:54:05.160714+02:00

### Get shopping candidates from postgres

In [64]:
# Query the postgres view
query = "SELECT * FROM letterboxd.shop_candidates;"

# Read into DataFrame
df = pd.read_sql(query, con=engine)

df

                      name  year        letterboxd_uri  rating
0        It Comes at Night  2017  https://boxd.it/eLuk     4.0
1                 The Gift  2015  https://boxd.it/aJMy     4.0
2            Speak No Evil  2022  https://boxd.it/vqlg     4.0
3    2001: A Space Odyssey  1968  https://boxd.it/2bf0     4.0
4                The Thing  1982  https://boxd.it/294O     4.0
..                     ...   ...                   ...     ...
221    Night at the Museum  2006  https://boxd.it/28wi     3.5
222     Memories of Murder  2003  https://boxd.it/1TSo     3.5
223             The Invite  2026  https://boxd.it/zRNY     4.5
224       Wake Up Dead Man  2025  https://boxd.it/uAKS     4.0
225         Lords of Chaos  2018  https://boxd.it/f5no     4.0

[226 rows x 4 columns]