In [19]:
import sys
import asyncio
import json
import os
import time
import random
from datetime import datetime
import pytz
from concurrent.futures import ThreadPoolExecutor

import pandas as pd
from bs4 import BeautifulSoup
from camoufox.sync_api import Camoufox
from curl_cffi import requests
from sqlalchemy import MetaData, Table, create_engine, insert
from sqlalchemy.dialects.postgresql import insert

### Get postgres data

In [6]:
PG_PASSWORD = os.environ.get('postgres_password')

if not PG_PASSWORD:
    raise ValueError("Postgres password environment variable not found!")

In [23]:
# Create connection engine for postgres
engine = create_engine(f"postgresql://postgres:{PG_PASSWORD}@localhost:5432/moviedata")

# Query the postgres view
query = "SELECT * FROM public.shop_candidates;"

# Read into DataFrame
df_shop_candidates = (
    pd.read_sql(query, con=engine)
    .sort_values(['watched','derived_rating'], ascending=False)
    .reset_index()
)

df_shop_candidates

,index,name,letterboxd_uri,title,derived_rating,watched
0,8,Galaxy Quest,https://boxd.it/29gq,Galaxy Quest - Planlos durchs Weltall,10.00,True
1,23,The Banshees of Inisherin,https://boxd.it/p7XS,The Banshees of Inisherin,10.00,True
2,70,The Death of Stalin,https://boxd.it/ea9Y,The Death of Stalin,9.00,True
3,153,Flow,https://boxd.it/v1Ei,Flow,9.00,True
4,174,Mad God,https://boxd.it/vVPm,Mad God,9.00,True
...,...,...,...,...,...,...
352,212,Micmacs,https://boxd.it/1qCQ,Micmacs - Uns gehört Paris!,7.25,False
353,253,Evil Dead Burn,https://boxd.it/K1R2,Evil Dead Burn,7.25,False
354,263,Bringing Out the Dead,https://boxd.it/1ZZK,Bringing Out the Dead - Nächte der Erinnerung,7.20,False
355,250,From Beyond,https://boxd.it/1NXi,From Beyond - Aliens des Grauens,7.15,False
356,331,Never Let Me Go,https://boxd.it/Xw0,"Alles, was wir geben mussten",7.05,False

### Get Medimops user agent and cookies

In [13]:
def get_rottentomatoes_useragent(max_retries=3):
    # Fix for Windows asyncio subprocesses in background threads
    print("[INFO] Medimops useragent and cookie aquisition started.")
    print("[INFO] Fixing windows asyncio for Jupyter notebook...")
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    # ================================================================================
    def _connect():
        """
        """
        try:
            print("[INFO] Launching Camoufox...")
            with Camoufox(headless=True) as browser:
                page = browser.new_page()

                # ----------------------------------------------------------------------
                # Sign in
                print("[INFO] Loading main page...")
                page.goto("https://www.medimops.de", wait_until="networkidle")

                # ----------------------------------------------------------------------
                # Export browser session details for curl
                user_agent = page.evaluate("navigator.userAgent")
                cookies = page.context.cookies()

                print("[INFO] User agent and cookies succesfully obtained!")

            # Return buffered data, user_agent and cookies
            return user_agent, cookies
        except Exception as e:
            print("[WARNING] Camoufox failed! Returning empty result.")
            print(f"[WARNING] Camoufox exception: {e}")
            return None, None

    # ================================================================================
    err_cnt = 0
    for i in range(max_retries):
        print(f"[INFO] Attempting connection via Camoufox ({i+1}/{max_retries})...")
        # Execute in ThreadPoolExecutor for Jupyter compatibility
        with ThreadPoolExecutor(max_workers=1) as executor:
            user_agent, cookies = executor.submit(_connect).result()

        if (user_agent is not None) and (cookies is not None):
            return user_agent, cookies
        else:
            print(f"[WARNING] Connection attempt failed {i+1}/{max_retries}. Trying again...")
            err_cnt += 1

    if err_cnt == max_retries:
        print(f"[ERROR] Connection via camoufox failed {i+1}/{max_retries}! Aborting process...")
        raise RuntimeError(f"Failed to connect to letterboxd! Exceeded max. retries ({max_retries}).")

In [15]:
def create_session(user_agent, cookies) -> requests.Session:
    """
    Receives user_agent and cookies for letterboxd and creates a session
    for HTTP requests.
    """
    # Create session
    session = requests.Session(impersonate="chrome124")

    # 1. Update User-Agent
    session.headers.update({"User-Agent": user_agent})

    # 2. Add all 9 cookies at once
    for cookie in cookies:
        session.cookies.set(
            name=cookie["name"],
            value=cookie["value"],
            domain=cookie.get("domain"),
            path=cookie.get("path", "/")
        )

    return session

## Scrape movie prices

In [21]:
def scrape_movie_prices(session: requests.Session, movie_title="Conclave"):
    """
    """
    # Add movie title + "blu ray" as search parameter
    params = {
            "searchparam" : f"{movie_title} blu ray",
            "fcIsSearch" : 1
            }
    
    # Query for movie data
    print("[INFO] Querying movie data...")
    response = session.get(
        # Use "Blu-ray" url to only get results for blu rays (no books, DVDs etc.)
        url="https://www.medimops.de/Blu-ray,/?condition=UsedVeryGood%2CUsedGood%2CNewItem%2CLibriNew",
        params=params
        )

    # Extract the product data from full SSR HTML
    print("[INFO] Parsing soup...")
    soup = BeautifulSoup(response.text, "html.parser")

    offers_metadata = []

    # ------------------------------------------------------------------------------------
    found_titles = soup.find_all(class_="ProductSearch_title__RhpT3")
    print(f"[INFO] Found {len(found_titles)} titles!")

    for i,el in enumerate(found_titles):
        offers_metadata.append({
            'rank':i,
            'title':el.text,
            })

    # ------------------------------------------------------------------------------------
    found_pricing = soup.find_all(class_="ProductSearch_price__N58Fa")
    print(f"[INFO] Found {len(found_pricing)} prices!")

    def _get_price(elem):
        txt = (
            elem.text
            .replace("\xa0", " ")
            .replace("€","")
            .replace(",",".")
            .strip()
        )
        return float(txt)

    found_pricing_clean = [(_get_price(c), _get_price(p)) for c, p in zip(found_pricing[::2], found_pricing[1::2])]

    if len(found_pricing_clean) != len(found_titles):
        print("[WARNING] Number of prices does not match number of titles!")
    else:
        for md, el in zip(offers_metadata, found_pricing_clean):
            md['price_mobile'] = el[0]
            md['price_desktop'] = el[0]

    # ------------------------------------------------------------------------------------
    found_conditions = soup.find_all(class_="ProductSearch_condition__810YM ProductSearch_flexColumn__HBtVh mobile-only")
    print(f"[INFO] Found {len(found_conditions)} conditions!")

    if len(found_titles) != len(found_conditions):
        print("[WARNING] Number of conditions does not match number of titles!")
    else:
        for md, el in zip(offers_metadata, found_conditions):
            md['condition'] = el.text

    return offers_metadata

### Create session object

Create a session object to reuse TLP/TCP connections etc. accross multiple requests

In [6]:
# Create a persistent session to hold tokens across requests
session = requests.Session()

session.headers.update({
    "User-Agent": user_agent,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
})

session.cookies.update(cookies)
session.impersonate = "chrome124"  # Best match for Camoufox

### Query page

In [40]:
# --------------------------------------------------------------------------------
movie_title = "No country for old men"

res = scrape_movie_prices(session, movie_title=movie_title)

[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 12 titles!
[INFO] Found 24 prices!
[INFO] Found 12 conditions!

In [39]:
df_res = pd.DataFrame(res)

# Get title without any form of "blu ray"
title_clean = (
    df_res['title']
    .str.lower()
    .str.replace(r"([^\w\s])?(bl.+ay+)([^\w\s])?", "", regex=True)
)

# Check if requested movie title appears in scraped title
sel_a = title_clean.apply(lambda x: movie_title.lower() in x)
# Check if scraped title appears in requested movie title
sel_b = title_clean.apply(lambda x: x in movie_title.lower())

# If either is True then search is matching
# If both are False then search is wrong
# (e.g. "Oldboy" returns when searching for "No Country For Old Men")
sel = sel_a | sel_b

df_res_clean = df_res.loc[sel,:].reset_index(drop=True)
tz = pytz.timezone('Europe/Berlin')
df_res_clean['timestamp_query'] = datetime.now(tz)

df_res_clean['letterboxd_name'] = "???"
df_res_clean['letterboxd_uri'] = "???"

df_res_clean

,rank,title,price_mobile,price_desktop,condition,timestamp_query,letterboxd_name,letterboxd_uri
0,0,No Country For Old Men [Blu-ray],5.49,5.49,Gebraucht - Sehr gut,2026-08-28 13:25:01.363348+02:00,???,???
1,1,No Country for Old Men [Blu-ray],7.79,7.79,Gebraucht - Sehr gut,2026-08-28 13:25:01.363348+02:00,???,???
2,2,No Country For Old Men (Limitierte Steelbook E...,14.89,14.89,Gebraucht - Sehr gut,2026-08-28 13:25:01.363348+02:00,???,???
3,3,No country for old men [Blu-ray],12.59,12.59,Gebraucht - Sehr gut,2026-08-28 13:25:01.363348+02:00,???,???
4,7,OLD [Blu-ray],6.99,6.99,Gebraucht - Sehr gut,2026-08-28 13:25:01.363348+02:00,???,???

In [34]:
# Get user agent and cookies
user_agent, cookies = get_rottentomatoes_useragent(max_retries=3)
# Create session object
session = create_session(user_agent, cookies)

# Create temporary DF that is used for scraping
df_scrape = df_shop_candidates.copy()

for i, row in df_scrape.iterrows():
    print("------------------------------------------------------------")
    print(f"[INFO] [{i+1}/{df_scrape.shape[0]}] Processing: EN: {row['name']} / DE: {row['title']}")

    movie_title = row['title']
    # 
    try:
        res = scrape_movie_prices(session, movie_title=movie_title)
        if len(res)>0:
            print("[INFO] Scrape successful!")
        else:
            print("[WARNING] Scrape worked but empty results! Skipping movie...")
            continue
    except:
        print("[WARNING] Scrape failed! Skipping movie...")
        continue

    # ------------------------------------------------------------
    # SCRAPE POSTPROCESS

    # Convert scrape result (list of dictionaries) to Pandas DF
    df_res = pd.DataFrame(res)

    # Get title without any form of "blu ray"
    title_clean = (
        df_res['title']
        .str.lower()
        .str.replace(r"([^\w\s])?(bl.+ay+)([^\w\s])?", "", regex=True)
    )

    # Check if requested movie title appears in scraped title
    sel_a = title_clean.apply(lambda x: movie_title.lower() in x)
    # Check if scraped title appears in requested movie title
    sel_b = title_clean.apply(lambda x: x in movie_title.lower())

    # If either is True then search is matching
    # If both are False then search is wrong
    # (e.g. "Oldboy" returns when searching for "No Country For Old Men")
    sel = sel_a | sel_b
    df_res_clean = df_res.loc[sel,:].reset_index(drop=True)

    if df_res_clean.shape[0] == 0:
        print("[WARNING] No search result matched the movie title! Skipping movie...")
        continue

    print(f"[INFO] Found {df_res_clean.shape[0]} matching search results!")

    # Add current timestamp
    tz = pytz.timezone('Europe/Berlin')
    df_res_clean['timestamp_query'] = datetime.now(tz)

    # Add letterboxd information
    df_res_clean['letterboxd_name'] = row['name']
    df_res_clean['letterboxd_uri'] = row['letterboxd_uri']

    # -----------------------------------------------------------------
    # Write movie metadata DataFrame to postgres table
    print("[INFO] Writing movie metadata DataFrame to postgres db...")

    try:
        # Use pandas to_sql to write the DataFrame
        df_res_clean.to_sql(
            name="shop_candidates",
            con=engine,
            schema="medimops",
            if_exists="append",  # Appends to the table without dropping/recreating it
            index=False           # Excludes the pandas DataFrame index from being written as a column
        )
        print("[INFO] Movie metadata succesfully written to database!")
        print("\n")
    except Exception as e:
        print(f"[WARNING] Failed to write to database for {row['name']}! Continuing with next movie...")

    # Wait a little bit. Do it randomly be less suspicious
    time.sleep(random.random()*1.0)

[INFO] Medimops useragent and cookie aquisition started.
[INFO] Fixing windows asyncio for Jupyter notebook...
[INFO] Attempting connection via Camoufox (1/3)...
[INFO] Launching Camoufox...
[INFO] Loading main page...
[INFO] User agent and cookies succesfully obtained!
------------------------------------------------------------
[INFO] [1/357] Processing: EN: Galaxy Quest / DE: Galaxy Quest - Planlos durchs Weltall
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 30 titles!
[INFO] Found 60 prices!
[INFO] Found 30 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [2/357] Processing: EN: The Banshees of Inisherin / DE: The Banshees of Inisherin
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 30 titles!
[INFO] Found 60 prices!
[INFO] Found 30 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [3/357] Processing: EN: The Death of Stalin / DE: The Death of Stalin
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 30 titles!
[INFO] Found 60 prices!
[INFO] Found 30 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [4/357] Processing: EN: Flow / DE: Flow
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 30 titles!
[INFO] Found 60 prices!
[INFO] Found 30 conditions!
[INFO] Scrape successful!
[INFO] Found 10 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [5/357] Processing: EN: Mad God / DE: Mad God
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 26 titles!
[INFO] Found 52 prices!
[INFO] Found 26 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [6/357] Processing: EN: The Odyssey / DE: Die Odyssee
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 21 titles!
[INFO] Found 42 prices!
[INFO] Found 21 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [7/357] Processing: EN: The Invite / DE: The Invite
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [8/357] Processing: EN: It Comes at Night / DE: It Comes at Night
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 24 titles!
[INFO] Found 48 prices!
[INFO] Found 24 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [9/357] Processing: EN: The Gift / DE: The Gift
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 13 titles!
[INFO] Found 26 prices!
[INFO] Found 13 conditions!
[INFO] Scrape successful!
[INFO] Found 4 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [10/357] Processing: EN: Speak No Evil / DE: Speak No Evil
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 13 titles!
[INFO] Found 26 prices!
[INFO] Found 13 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [11/357] Processing: EN: 2001: A Space Odyssey / DE: 2001: Odyssee im Weltraum
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 8 titles!
[INFO] Found 16 prices!
[INFO] Found 8 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [12/357] Processing: EN: The Thing / DE: Das Ding aus einer anderen Welt
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [13/357] Processing: EN: The Martian / DE: Der Marsianer - Rettet Mark Watney
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 2 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [14/357] Processing: EN: Twelve Monkeys / DE: 12 Monkeys
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 17 titles!
[INFO] Found 34 prices!
[INFO] Found 17 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [15/357] Processing: EN: A.I. Artificial Intelligence / DE: A.I. - Künstliche Intelligenz
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 12 titles!
[INFO] Found 24 prices!
[INFO] Found 12 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [16/357] Processing: EN: THX 1138 / DE: THX 1138
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 2 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [17/357] Processing: EN: The Hitchhiker's Guide to the Galaxy / DE: Per Anhalter durch die Galaxis
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 14 titles!
[INFO] Found 28 prices!
[INFO] Found 14 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [18/357] Processing: EN: The Guilty / DE: The Guilty
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 19 titles!
[INFO] Found 38 prices!
[INFO] Found 19 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for The Guilty! Continuing with next movie...
------------------------------------------------------------
[INFO] [19/357] Processing: EN: Bird Box / DE: Bird Box - Schließe deine Augen
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 19 titles!
[INFO] Found 38 prices!
[INFO] Found 19 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [20/357] Processing: EN: Signs / DE: Signs - Zeichen
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 13 titles!
[INFO] Found 26 prices!
[INFO] Found 13 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [21/357] Processing: EN: The Lobster / DE: The Lobster
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 27 titles!
[INFO] Found 54 prices!
[INFO] Found 27 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [22/357] Processing: EN: Black Swan / DE: Black Swan
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 18 titles!
[INFO] Found 36 prices!
[INFO] Found 18 conditions!
[INFO] Scrape successful!
[INFO] Found 14 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Black Swan! Continuing with next movie...
------------------------------------------------------------
[INFO] [23/357] Processing: EN: Pulp Fiction / DE: Pulp Fiction
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 7 titles!
[INFO] Found 14 prices!
[INFO] Found 7 conditions!
[INFO] Scrape successful!
[INFO] Found 7 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Pulp Fiction! Continuing with next movie...
------------------------------------------------------------
[INFO] [24/357] Processing: EN: The Menu / DE: The Menu
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 30 titles!
[INFO] Found 60 prices!
[INFO] Found 30 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [25/357] Processing: EN: The Truman Show / DE: Die Truman Show
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 18 titles!
[INFO] Found 36 prices!
[INFO] Found 18 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [26/357] Processing: EN: American Psycho / DE: American Psycho
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 16 titles!
[INFO] Found 32 prices!
[INFO] Found 16 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [27/357] Processing: EN: The Silence of the Lambs / DE: Das Schweigen der Lämmer
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 2 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [28/357] Processing: EN: The Grand Budapest Hotel / DE: Grand Budapest Hotel
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 17 titles!
[INFO] Found 34 prices!
[INFO] Found 17 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [29/357] Processing: EN: Oldboy / DE: Oldboy
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 18 titles!
[INFO] Found 36 prices!
[INFO] Found 18 conditions!
[INFO] Scrape successful!
[INFO] Found 5 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Oldboy! Continuing with next movie...
------------------------------------------------------------
[INFO] [30/357] Processing: EN: Superbad / DE: Superbad
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 26 titles!
[INFO] Found 52 prices!
[INFO] Found 26 conditions!
[INFO] Scrape successful!
[INFO] Found 3 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Superbad! Continuing with next movie...
------------------------------------------------------------
[INFO] [31/357] Processing: EN: Ratatouille / DE: Ratatouille
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 9 titles!
[INFO] Found 18 prices!
[INFO] Found 9 conditions!
[INFO] Scrape successful!
[INFO] Found 9 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Ratatouille! Continuing with next movie...
------------------------------------------------------------
[INFO] [32/357] Processing: EN: Forrest Gump / DE: Forrest Gump
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 8 titles!
[INFO] Found 16 prices!
[INFO] Found 8 conditions!
[INFO] Scrape successful!
[INFO] Found 7 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [33/357] Processing: EN: Gladiator / DE: Gladiator
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 27 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Gladiator! Continuing with next movie...
------------------------------------------------------------
[INFO] [34/357] Processing: EN: City of God / DE: City of God
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 13 titles!
[INFO] Found 26 prices!
[INFO] Found 13 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [35/357] Processing: EN: The Departed / DE: Departed - Unter Feinden
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [36/357] Processing: EN: Catch Me If You Can / DE: Catch Me If You Can
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 8 titles!
[INFO] Found 16 prices!
[INFO] Found 8 conditions!
[INFO] Scrape successful!
[INFO] Found 2 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [37/357] Processing: EN: Full Metal Jacket / DE: Full Metal Jacket
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 12 titles!
[INFO] Found 24 prices!
[INFO] Found 12 conditions!
[INFO] Scrape successful!
[INFO] Found 8 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Full Metal Jacket! Continuing with next movie...
------------------------------------------------------------
[INFO] [38/357] Processing: EN: Pirates of the Caribbean: The Curse of the Black Pearl / DE: Fluch der Karibik
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 27 titles!
[INFO] Found 54 prices!
[INFO] Found 27 conditions!
[INFO] Scrape successful!
[INFO] Found 5 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [39/357] Processing: EN: Kingsman: The Secret Service / DE: Kingsman: The Secret Service
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 27 titles!
[INFO] Found 54 prices!
[INFO] Found 27 conditions!
[INFO] Scrape successful!
[INFO] Found 2 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [40/357] Processing: EN: Ocean's Eleven / DE: Ocean's Eleven
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 14 titles!
[INFO] Found 28 prices!
[INFO] Found 14 conditions!
[INFO] Scrape successful!
[INFO] Found 4 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [41/357] Processing: EN: WALL·E / DE: WALL·E - Der Letzte räumt die Erde auf
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 21 titles!
[INFO] Found 42 prices!
[INFO] Found 21 conditions!
[INFO] Scrape successful!
[WARNING] No search result matched the movie title! Skipping movie...
------------------------------------------------------------
[INFO] [42/357] Processing: EN: Léon: The Professional / DE: Léon - Der Profi
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 27 titles!
[INFO] Found 54 prices!
[INFO] Found 27 conditions!
[INFO] Scrape successful!
[INFO] Found 1 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [43/357] Processing: EN: Monsters, Inc. / DE: Die Monster AG
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 6 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Monsters, Inc.! Continuing with next movie...
------------------------------------------------------------
[INFO] [44/357] Processing: EN: Apocalypse Now / DE: Apocalypse Now
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 21 titles!
[INFO] Found 42 prices!
[INFO] Found 21 conditions!
[INFO] Scrape successful!
[INFO] Found 13 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------
[INFO] [45/357] Processing: EN: Kung Fu Panda / DE: Kung Fu Panda
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 29 titles!
[INFO] Found 58 prices!
[INFO] Found 29 conditions!
[INFO] Scrape successful!
[INFO] Found 29 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[WARNING] Failed to write to database for Kung Fu Panda! Continuing with next movie...
------------------------------------------------------------
[INFO] [46/357] Processing: EN: The Fast and the Furious / DE: The Fast and the Furious
[INFO] Querying movie data...
[INFO] Parsing soup...
[INFO] Found 28 titles!
[INFO] Found 56 prices!
[INFO] Found 28 conditions!
[INFO] Scrape successful!
[INFO] Found 6 matching search results!
[INFO] Writing movie metadata DataFrame to postgres db...
[INFO] Movie metadata succesfully written to database!


------------------------------------------------------------